In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df=pd.read_csv('train_data.csv')
test_df=pd.read_csv('test_data.csv')

In [3]:
train_df.head(10)

connection_id  cont_1  cont_2  cont_3  cont_4  cont_5  cont_6  cont_7  \
0       cxcon_1       0    1032       0     0.0     0.0     0.0     0.0   
1       cxcon_4       0     520       0     0.0     0.0     0.0     0.0   
2       cxcon_7       0    1032       0     0.0     0.0     0.0     0.0   
3      cxcon_10       0    1032       0     0.0     0.0     0.0     0.0   
4      cxcon_13       0    1032       0     0.0     0.0     0.0     0.0   
5      cxcon_16       0    1032       0     0.0     0.0     0.0     0.0   
6      cxcon_19       0     219    7662     0.0     0.0     0.0     0.0   
7      cxcon_22       0    1032       0     0.0     0.0     0.0     0.0   
8      cxcon_25       0       0       0     1.0     1.0     0.0     0.0   
9      cxcon_28       0     105       0     0.0     0.0     0.0     0.0   

   cont_8  cont_9  ...  cat_15  cat_16  cat_17  cat_18  cat_19  cat_20  \
0    1.00    0.00  ...       0       0       0       0       0     511   
1    1.00    0.00  ...       0       0       0       0       0     511   
2    1.00    0.00  ...       0       0       0       0       0     511   
3    1.00    0.00  ...       0       0       0       0       0     511   
4    1.00    0.00  ...       0       0       0       0       0     511   
5    1.00    0.00  ...       0       0       0       0       0     511   
6    1.00    0.00  ...       0       0       0       0       0       3   
7    1.00    0.00  ...       0       0       0       0       0     511   
8    0.05    0.07  ...       0       0       0       0       0     221   
9    1.00    0.00  ...       0       0       0       0       0       2   

   cat_21  cat_22  cat_23  target  
0     511     255     255       2  
1     511     255     255       0  
2     511     255     255       0  
3     511     255     255       0  
4     511     255     255       2  
5     511     255     255       0  
6       3     255     255       1  
7     511     255     255       2  
8      11     255      11       0  
9       2     255     246       1  

[10 rows x 43 columns]

In [4]:
test_df.head(10)

connection_id  cont_1  cont_2  cont_3  cont_4  cont_5  cont_6  cont_7  \
0       cxcon_2       0     331    6085     0.0     0.0     0.0     0.0   
1       cxcon_5       0     520       0     0.0     0.0     0.0     0.0   
2       cxcon_8       0    1032       0     0.0     0.0     0.0     0.0   
3      cxcon_11       0    1032       0     0.0     0.0     0.0     0.0   
4      cxcon_14       0    1032       0     0.0     0.0     0.0     0.0   
5      cxcon_17       0    1032       0     0.0     0.0     0.0     0.0   
6      cxcon_20       0       0       0     0.0     0.0     1.0     1.0   
7      cxcon_23       0     332     743     0.0     0.0     0.0     0.0   
8      cxcon_26       0    1032       0     0.0     0.0     0.0     0.0   
9      cxcon_29       0    1032       0     0.0     0.0     0.0     0.0   

   cont_8  cont_9  ...  cat_14  cat_15  cat_16  cat_17  cat_18  cat_19  \
0    1.00    0.00  ...       0       0       0       0       0       0   
1    1.00    0.00  ...       0       0       0       0       0       0   
2    1.00    0.00  ...       0       0       0       0       0       0   
3    1.00    0.00  ...       0       0       0       0       0       0   
4    1.00    0.00  ...       0       0       0       0       0       0   
5    1.00    0.00  ...       0       0       0       0       0       0   
6    0.04    0.06  ...       0       0       0       0       0       0   
7    1.00    0.00  ...       0       0       0       0       0       0   
8    1.00    0.00  ...       0       0       0       0       0       0   
9    1.00    0.00  ...       0       0       0       0       0       0   

   cat_20  cat_21  cat_22  cat_23  
0      13      13     255     255  
1     511     511     255     255  
2     511     511     255     255  
3     510     509     255     255  
4     511     511     255     255  
5     511     511     255     255  
6     187       7     255       7  
7      30      30     180     255  
8     511     511     255     255  
9     511     511     255     255  

[10 rows x 42 columns]

In [5]:
train_df.shape

(169307, 43)

In [6]:
test_df.shape

(91166, 42)

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169307 entries, 0 to 169306
Data columns (total 43 columns):
connection_id    169307 non-null object
cont_1           169307 non-null int64
cont_2           169307 non-null int64
cont_3           169307 non-null int64
cont_4           169307 non-null float64
cont_5           169307 non-null float64
cont_6           169307 non-null float64
cont_7           169307 non-null float64
cont_8           169307 non-null float64
cont_9           169307 non-null float64
cont_10          169307 non-null float64
cont_11          169307 non-null float64
cont_12          169307 non-null float64
cont_13          169307 non-null float64
cont_14          169307 non-null float64
cont_15          169307 non-null float64
cont_16          169307 non-null float64
cont_17          169307 non-null float64
cont_18          169307 non-null float64
cat_1            169307 non-null int64
cat_2            169307 non-null int64
cat_3            169307 non-null int64


In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91166 entries, 0 to 91165
Data columns (total 42 columns):
connection_id    91166 non-null object
cont_1           91166 non-null int64
cont_2           91166 non-null int64
cont_3           91166 non-null int64
cont_4           91166 non-null float64
cont_5           91166 non-null float64
cont_6           91166 non-null float64
cont_7           91166 non-null float64
cont_8           91166 non-null float64
cont_9           91166 non-null float64
cont_10          91166 non-null float64
cont_11          91166 non-null float64
cont_12          91166 non-null float64
cont_13          91166 non-null float64
cont_14          91166 non-null float64
cont_15          91166 non-null float64
cont_16          91166 non-null float64
cont_17          91166 non-null float64
cont_18          91166 non-null float64
cat_1            91166 non-null int64
cat_2            91166 non-null int64
cat_3            91166 non-null int64
cat_4            91166 n

In [9]:
train_df.isnull().sum()

connection_id    0
cont_1           0
cont_2           0
cont_3           0
cont_4           0
cont_5           0
cont_6           0
cont_7           0
cont_8           0
cont_9           0
cont_10          0
cont_11          0
cont_12          0
cont_13          0
cont_14          0
cont_15          0
cont_16          0
cont_17          0
cont_18          0
cat_1            0
cat_2            0
cat_3            0
cat_4            0
cat_5            0
cat_6            0
cat_7            0
cat_8            0
cat_9            0
cat_10           0
cat_11           0
cat_12           0
cat_13           0
cat_14           0
cat_15           0
cat_16           0
cat_17           0
cat_18           0
cat_19           0
cat_20           0
cat_21           0
cat_22           0
cat_23           0
target           0
dtype: int64

In [10]:
test_df.isnull().sum()

connection_id    0
cont_1           0
cont_2           0
cont_3           0
cont_4           0
cont_5           0
cont_6           0
cont_7           0
cont_8           0
cont_9           0
cont_10          0
cont_11          0
cont_12          0
cont_13          0
cont_14          0
cont_15          0
cont_16          0
cont_17          0
cont_18          0
cat_1            0
cat_2            0
cat_3            0
cat_4            0
cat_5            0
cat_6            0
cat_7            0
cat_8            0
cat_9            0
cat_10           0
cat_11           0
cat_12           0
cat_13           0
cat_14           0
cat_15           0
cat_16           0
cat_17           0
cat_18           0
cat_19           0
cat_20           0
cat_21           0
cat_22           0
cat_23           0
dtype: int64

In [11]:
train_df.columns

Index(['connection_id', 'cont_1', 'cont_2', 'cont_3', 'cont_4', 'cont_5',
       'cont_6', 'cont_7', 'cont_8', 'cont_9', 'cont_10', 'cont_11', 'cont_12',
       'cont_13', 'cont_14', 'cont_15', 'cont_16', 'cont_17', 'cont_18',
       'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8',
       'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15',
       'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22',
       'cat_23', 'target'],
      dtype='object')

In [12]:
test_df.columns

Index(['connection_id', 'cont_1', 'cont_2', 'cont_3', 'cont_4', 'cont_5',
       'cont_6', 'cont_7', 'cont_8', 'cont_9', 'cont_10', 'cont_11', 'cont_12',
       'cont_13', 'cont_14', 'cont_15', 'cont_16', 'cont_17', 'cont_18',
       'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8',
       'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15',
       'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22',
       'cat_23'],
      dtype='object')

In [13]:
train_df['target'].value_counts()

0    98868
2    36854
1    33585
Name: target, dtype: int64

In [14]:
train_df[['cat_1','cat_2','cat_3','cat_4','cat_5','cat_6','cat_7','cat_8','cat_9','cat_10','cat_11','cat_12','cat_13',
          'cat_14','cat_15','cat_16','cat_17','cat_18','cat_19','cat_20','cat_21',
          'cat_22','cat_23','target']]=train_df[['cat_1','cat_2','cat_3','cat_4','cat_5','cat_6',
                                                 'cat_7','cat_8','cat_9','cat_10','cat_11','cat_12','cat_13','cat_14',
                                                 'cat_15','cat_16','cat_17','cat_18','cat_19','cat_20','cat_21',
                                                 'cat_22','cat_23','target']].astype(object)

In [15]:
test_df[['cat_1','cat_2','cat_3','cat_4','cat_5','cat_6','cat_7','cat_8','cat_9','cat_10','cat_11','cat_12','cat_13',
          'cat_14','cat_15','cat_16','cat_17','cat_18','cat_19','cat_20','cat_21',
          'cat_22','cat_23']]=test_df[['cat_1','cat_2','cat_3','cat_4','cat_5','cat_6',
                                                 'cat_7','cat_8','cat_9','cat_10','cat_11','cat_12','cat_13','cat_14',
                                                 'cat_15','cat_16','cat_17','cat_18','cat_19','cat_20','cat_21',
                                                 'cat_22','cat_23']].astype(object)

In [16]:
num_data=train_df.describe()
num_data

cont_1        cont_2        cont_3         cont_4  \
count  169307.000000  1.693070e+05  1.693070e+05  169307.000000   
mean       44.136722  1.077011e+03  7.501477e+02       0.171399   
std       659.337783  4.302746e+04  3.527929e+04       0.376214   
min         0.000000  0.000000e+00  0.000000e+00       0.000000   
25%         0.000000  4.500000e+01  0.000000e+00       0.000000   
50%         0.000000  5.200000e+02  0.000000e+00       0.000000   
75%         0.000000  1.032000e+03  0.000000e+00       0.000000   
max     42596.000000  1.139690e+07  1.173059e+07       1.000000   

              cont_5         cont_6         cont_7         cont_8  \
count  169307.000000  169307.000000  169307.000000  169307.000000   
mean        0.171479       0.062442       0.062478       0.791319   
std         0.376593       0.241000       0.241354       0.388389   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       1.000000   
50%         0.000000       0.000000       0.000000       1.000000   
75%         0.000000       0.000000       0.000000       1.000000   
max         1.000000       1.000000       1.000000       1.000000   

              cont_9        cont_10        cont_11        cont_12  \
count  169307.000000  169307.000000  169307.000000  169307.000000   
mean        0.021317       0.028090       0.755858       0.030386   
std         0.084299       0.139745       0.409922       0.107547   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.480000       0.000000   
50%         0.000000       0.000000       1.000000       0.000000   
75%         0.000000       0.000000       1.000000       0.040000   
max         1.000000       1.000000       1.000000       1.000000   

             cont_13        cont_14        cont_15        cont_16  \
count  169307.000000  169307.000000  169307.000000  169307.000000   
mean        0.601241       0.006442       0.171599       0.171341   
std         0.481976       0.041425       0.376159       0.376465   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         1.000000       0.000000       0.000000       0.000000   
75%         1.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

             cont_17        cont_18  
count  169307.000000  169307.000000  
mean        0.062712       0.062327  
std         0.239591       0.239554  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000

In [17]:
corr_data=num_data -(num_data.mean()/num_data.std())

In [18]:
corr_data

cont_1        cont_2        cont_3         cont_4  \
count  169306.553778  1.693066e+05  1.693066e+05  169306.646443   
mean       43.690500  1.076650e+03  7.497871e+02      -0.182158   
std       658.891560  4.302710e+04  3.527892e+04       0.022656   
min        -0.446222 -3.611586e-01 -3.606080e-01      -0.353557   
25%        -0.446222  4.463884e+01 -3.606080e-01      -0.353557   
50%        -0.446222  5.196388e+02 -3.606080e-01      -0.353557   
75%        -0.446222  1.031639e+03 -3.606080e-01      -0.353557   
max     42595.553778  1.139690e+07  1.173059e+07       0.646443   

              cont_5         cont_6         cont_7         cont_8  \
count  169306.646443  169306.646443  169306.646443  169306.646434   
mean       -0.182078      -0.291115      -0.291078       0.437753   
std         0.023036      -0.112556      -0.112203       0.034823   
min        -0.353557      -0.353557      -0.353557      -0.353566   
25%        -0.353557      -0.353557      -0.353557       0.646434   
50%        -0.353557      -0.353557      -0.353557       0.646434   
75%        -0.353557      -0.353557      -0.353557       0.646434   
max         0.646443       0.646443       0.646443       0.646434   

              cont_9        cont_10        cont_11        cont_12  \
count  169306.646444  169306.646444  169306.646436  169306.646444   
mean       -0.332239      -0.325467       0.402294      -0.323170   
std        -0.269257      -0.213811       0.056358      -0.246009   
min        -0.353556      -0.353556      -0.353564      -0.353556   
25%        -0.353556      -0.353556       0.126436      -0.353556   
50%        -0.353556      -0.353556       0.646436      -0.353556   
75%        -0.353556      -0.353556       0.646436      -0.313556   
max         0.646444       0.646444       0.646436       0.646444   

             cont_13        cont_14        cont_15        cont_16  \
count  169306.646437  169306.646444  169306.646443  169306.646443   
mean        0.247678      -0.347114      -0.181958      -0.182216   
std         0.128413      -0.312131       0.022601       0.022908   
min        -0.353563      -0.353556      -0.353557      -0.353557   
25%        -0.353563      -0.353556      -0.353557      -0.353557   
50%         0.646437      -0.353556      -0.353557      -0.353557   
75%         0.646437      -0.353556      -0.353557      -0.353557   
max         0.646437       0.646444       0.646443       0.646443   

             cont_17        cont_18  
count  169306.646444  169306.646444  
mean       -0.290844      -0.291229  
std        -0.113966      -0.114002  
min        -0.353556      -0.353556  
25%        -0.353556      -0.353556  
50%        -0.353556      -0.353556  
75%        -0.353556      -0.353556  
max         0.646444       0.646444

In [19]:
cat_data=train_df.describe(include=['O'])
__target=cat_data.target
cat_data=cat_data.drop('target',axis=1)
cat_data

connection_id   cat_1   cat_2   cat_3   cat_4   cat_5   cat_6   cat_7  \
count         169307  169307  169307  169307  169307  169307  169307  169307   
unique        169307       3      64      11       2       3       2      18   
top      cxcon_58807       3      10       1       0       0       0       0   
freq               1   97394   96680  129734  169305  169265  169306  168972   

         cat_8   cat_9  ...  cat_14  cat_15  cat_16  cat_17  cat_18  cat_19  \
count   169307  169307  ...  169307  169307  169307  169307  169307  169307   
unique       2       2  ...      10       3       6       1       2       2   
top          0       0  ...       0       0       0       0       0       0   
freq    169289  144695  ...  169224  169295  169143  169307  169306  169160   

        cat_20  cat_21  cat_22  cat_23  
count   169307  169307  169307  169307  
unique     439     393     256     256  
top        511     511     255     255  
freq     77311   76871  148789  115863  

[4 rows x 24 columns]

In [20]:
cat_data['target'] = train_df["target"]

In [21]:
cat_data.columns

Index(['connection_id', 'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6',
       'cat_7', 'cat_8', 'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13',
       'cat_14', 'cat_15', 'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20',
       'cat_21', 'cat_22', 'cat_23', 'target'],
      dtype='object')

In [22]:
type(cat_data)

pandas.core.frame.DataFrame

In [23]:
cat = train_df.select_dtypes(exclude=[np.number])

In [24]:
cat.drop('connection_id',axis=1,inplace=True)

C:\Users\Atul\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [25]:
cat.columns

Index(['cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8',
       'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15',
       'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22',
       'cat_23', 'target'],
      dtype='object')

In [26]:
X=train_df.drop(['target'],axis=1)
y=train_df['target']
X=X.drop(['connection_id'],axis=1)

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,train_size=0.7,
                                                 random_state=1234)

In [28]:
X_train.columns

Index(['cont_1', 'cont_2', 'cont_3', 'cont_4', 'cont_5', 'cont_6', 'cont_7',
       'cont_8', 'cont_9', 'cont_10', 'cont_11', 'cont_12', 'cont_13',
       'cont_14', 'cont_15', 'cont_16', 'cont_17', 'cont_18', 'cat_1', 'cat_2',
       'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8', 'cat_9', 'cat_10',
       'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15', 'cat_16', 'cat_17',
       'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22', 'cat_23'],
      dtype='object')

In [29]:
X_valid.columns

Index(['cont_1', 'cont_2', 'cont_3', 'cont_4', 'cont_5', 'cont_6', 'cont_7',
       'cont_8', 'cont_9', 'cont_10', 'cont_11', 'cont_12', 'cont_13',
       'cont_14', 'cont_15', 'cont_16', 'cont_17', 'cont_18', 'cat_1', 'cat_2',
       'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8', 'cat_9', 'cat_10',
       'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15', 'cat_16', 'cat_17',
       'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22', 'cat_23'],
      dtype='object')

In [30]:
y_train=y_train.astype('int')
y_train

9528      0
67623     0
97556     0
19254     0
58753     0
30153     1
161731    0
49976     0
25256     0
15480     1
112791    1
140082    0
80108     0
154611    2
23722     0
87922     1
53231     0
10398     0
109588    0
158117    0
106306    0
74869     0
52371     2
17726     1
134103    0
36826     0
6660      0
122434    0
114502    0
100671    0
         ..
21225     0
23691     2
76519     1
50682     0
77734     2
152652    0
153339    0
134896    2
103986    2
167343    2
49398     0
117119    0
93520     0
73180     0
79728     0
125048    2
125370    2
73498     2
8060      2
40684     2
165022    0
139294    2
154778    2
9449      2
41239     1
55985     1
32399     2
82584     1
121909    0
165158    0
Name: target, Length: 118514, dtype: int32

In [31]:
y_valid=y_valid.astype('int')
y_valid

31513     0
79255     0
76489     0
137054    0
55920     2
150563    0
59986     0
147590    1
5011      0
78954     0
157489    0
76030     0
89470     0
9570      0
141893    0
35042     1
122506    2
136894    0
52658     2
8323      0
13510     2
129573    0
159171    1
28143     0
68672     2
138881    1
38212     1
42447     0
118103    0
98633     2
         ..
106701    0
142983    0
55335     0
18795     0
70528     0
142844    2
120129    1
3078      2
168826    0
149165    0
12669     0
39857     1
76164     0
71874     2
80021     0
164421    1
11239     0
76570     0
97853     1
34134     1
99976     0
145015    1
110899    1
72055     2
4850      0
82412     0
166565    0
79376     2
166505    0
87510     0
Name: target, Length: 50793, dtype: int32

# Accuracy test by applying all models

## Logistic regression classifier

In [44]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\Atul\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Atul\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Atul\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[29316   440    19]
 [   33  9971    23]
 [10824   160     7]]


0.7736105368850038

## decision tree classifier

In [46]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[27717    66  1992]
 [   29  9994     4]
 [10191    26   774]]


0.7576831453152993

## KNN classifier

In [58]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 2, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[28884    54   837]
 [  100  9927     0]
 [10629    18   344]]


0.7708739393223476

## kernal svm classifier

In [33]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\Atul\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[29458   292    25]
 [    1 10026     0]
 [10881   100    10]]


0.777548087334869

## naive bayes classifier

In [62]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [63]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[29247   361   167]
 [  353  9666     8]
 [10802   128    61]]


0.7673104561652196

## random forest classifier

In [64]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)

[[28087    65  1623]
 [   16 10011     0]
 [10331    26   634]]


0.7625460201208828

## support vector macchine

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_valid)
cm = confusion_matrix(y_valid, y_pred)
print(cm)
accuracy_score(y_valid, y_pred)